version: "3.9"

services:
  api:
    container_name: premierleague_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7024:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
      ConnectionStrings__DefaultConnection: "Server=host.docker.internal,1433;Database=EPL_DB;User Id=sa;Password=Pisethpt@100622;TrustServerCertificate=True;"
    depends_on:
      - redis

  redis:
    container_name: redis
    image: redis:7
    ports:
      - "6379:6379"