apiVersion: apps/v1
kind: Deployment
metadata:
  name: premierleague-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: premierleague-api
  template:
    metadata:
      labels:
        app: premierleague-api
    spec:
      containers:
        - name: api
          image: premierleague-api:1.0
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: ConnectionStrings__RedisConnection
              value: "redis:6379"
